import React from "react";
import Head from "next/head";
import UseState from "@/components/box/UseState";
import UseEffect from "@/components/box/UseEffect";
import UseReducer from "@/components/box/UseReducer";
import HookContainer from "@/components/box/HookContainer";

const test_hooks = () => {
  return (
    <div>
      <Head>
        <title>React Hooks Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <HookContainer />
        </div>
      </main>
    </div>
  );
};

export default test_hooks;
