import React from "react";
import Head from "next/head";
import Weather from "@/components/weather/Weather";

const weather = () => {
  return (
    <div>
      <Head>
        <title>WeatherApp Next Js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Weather />
        </div>
      </main>
    </div>
  );
};

export default weather;
